[package]
name = "tulipix-plugins"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
wasm = ["dep:wasmtime"]
lua = ["dep:mlua"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
wasmtime = { workspace = true, optional = true }
mlua = { workspace = true, optional = true }
