//! Flutter ↔ Rust bridge. One state type out, one command type in, one event
//! stream per section — not a mirror of the 6,668 Slint bindings.
//!
//! Everything under `api/` is what flutter_rust_bridge mirrors into Dart. The
//! rule for that module: plain owned data only. Bridge values cross a thread
//! boundary, so nothing in a state struct may be `Rc`/`!Send` the way Slint's
//! `ModelRc` is.

pub mod api;
mod db;

// Generated by `just --justfile justfile.flutter gen`. It does not exist on a
// fresh checkout, so the first `cargo check` after cloning fails until codegen
// has run once. That is the intended order, not a bug.
mod frb_generated;
