//! Flutter ↔ Rust bridge. One state type out, one command type in, one event
//! stream per section — not a mirror of the 6,668 Slint bindings.
//!
//! Everything under `api/` is what flutter_rust_bridge mirrors into Dart. The
//! rule for that module: plain owned data only. Bridge values cross a thread
//! boundary, so nothing in a state struct may be `Rc`/`!Send` the way Slint's
//! `ModelRc` is.

pub mod api;
mod db;
// Not under `api/`, so `rust_input: crate::api` never scans it: the mpv
// transport is an implementation detail of the Music section, not part of the
// Dart-facing contract.
mod mpv;
// Same reason: the Finances forms are a plain data structure the section builds
// and validates, not a Dart-facing type. `api::finances` maps them into the one
// struct that does cross.
mod fin_sheet;

// Generated by `just --justfile justfile.flutter gen`. It does not exist on a
// fresh checkout, so the first `cargo check` after cloning fails until codegen
// has run once. That is the intended order, not a bug.
mod frb_generated;
