//! Strict off-main-thread policy.
//!
//! Each long-running service (decode, thumb-gen, AI inference, IO) owns a
//! rayon worker pool sized from CPU topology + a service-specific cap. The
//! UI thread runs the Slint compositor only; any blocking call from the UI
//! thread is a bug, caught by:
//!
//!   * Runtime: `assert_off_main_thread!()` at the top of each service
//!     entrypoint; panics on violation in debug, logs in release.
//!   * Static: a workspace `clippy.toml` `disallowed-methods` entry blocks
//!     `std::thread::sleep`, `std::fs::*` and friends in the `tulipix-app`
//!     crate.
//!
//! Generated via `disallowed_methods_toml()` so CI can render the file
//! deterministically.

use std::cell::Cell;
use std::sync::OnceLock;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ServicePool {
    Decode,
    Thumb,
    Ai,
    Io,
    Scan,
}

impl ServicePool {
    /// Worker count: min(N, max), where N is half the logical CPUs (Decode/Thumb),
    /// quarter (Ai), or fixed (Io=4, Scan=2).
    pub fn worker_count(self, cpus: usize) -> usize {
        match self {
            ServicePool::Decode => (cpus / 2).clamp(1, 16),
            ServicePool::Thumb  => (cpus / 2).clamp(1, 16),
            ServicePool::Ai     => (cpus / 4).clamp(1,  8),
            ServicePool::Io     => 4,
            ServicePool::Scan   => 2,
        }
    }
}

thread_local! {
    static IS_MAIN: Cell<bool> = const { Cell::new(false) };
}
static MAIN_INITIALISED: OnceLock<()> = OnceLock::new();

/// Call once from `main()` on the UI thread.
pub fn mark_main_thread() {
    MAIN_INITIALISED.set(()).ok();
    IS_MAIN.with(|c| c.set(true));
}

pub fn on_main_thread() -> bool {
    IS_MAIN.with(|c| c.get())
}

#[macro_export]
macro_rules! assert_off_main_thread {
    () => {
        if $crate::perf::offthread::on_main_thread() {
            if cfg!(debug_assertions) {
                panic!("blocking call on UI thread");
            } else {
                tracing::error!("blocking call on UI thread");
            }
        }
    };
}

/// Render the project-root `clippy.toml` body that bans blocking methods
/// inside the UI crate.
pub fn disallowed_methods_toml() -> &'static str {
    r#"# Generated by tulipix-core::perf::offthread::disallowed_methods_toml.
# Run `just regen-clippy` to refresh.

disallowed-methods = [
  { path = "std::thread::sleep",      reason = "Blocks the UI thread. Use tokio::time::sleep on a worker pool." },
  { path = "std::fs::read",           reason = "Synchronous IO on the UI thread. Use tulipix-core::fs async helpers." },
  { path = "std::fs::read_to_string", reason = "Synchronous IO on the UI thread. Use tulipix-core::fs async helpers." },
  { path = "std::fs::write",          reason = "Synchronous IO on the UI thread. Use tulipix-core::fs async helpers." },
  { path = "std::process::Command::output", reason = "Blocks the UI thread. Spawn via tokio::process." },
  { path = "std::process::Command::status", reason = "Blocks the UI thread. Spawn via tokio::process." },
]
"#
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test] fn worker_counts_in_band() {
        assert!((1..=16).contains(&ServicePool::Decode.worker_count(32)));
        assert_eq!(ServicePool::Io.worker_count(32), 4);
        assert_eq!(ServicePool::Scan.worker_count(64), 2);
        assert_eq!(ServicePool::Ai.worker_count(2), 1);
    }
    #[test] fn main_thread_flag_default_false() {
        assert!(!on_main_thread());
    }
    #[test] fn clippy_toml_lists_thread_sleep() {
        assert!(disallowed_methods_toml().contains("std::thread::sleep"));
        assert!(disallowed_methods_toml().contains("std::fs::read"));
    }
}
